name: Go Module Release
run-name: ${{ github.actor }} is releasing a new Go Module version 🚀
on:
  push:
    branches:
      - develop
jobs:
  tag:
    name: Tag Go Module Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Current Code Base
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'
    - name: Create an incremental pre-release tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        PRERELEASE: true
        PRERELEASE_SUFFIX: "alpha"
  release:
    name: Release & Publish Go Module Version
    runs-on: ubuntu-latest
    needs: 
    - tag
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19' # The Go version to download (if necessary) and use.
    - run: GOPROXY=proxy.golang.org go list -m github.com/${{ github.repository }}@${{steps.tag.outputs.new_tag}}
  validate:
    name: Validate the Availability of Go Module Version
    needs: 
    - tag
    - release
    runs-on: ubuntu-latest
    steps:
    - run: curl https://sum.golang.org/lookup/github.com/${{ github.repository }}@${{steps.tag.outputs.new_tag}}