name: Go Module Release
run-name: ${{ github.actor }} is releasing a new Go Module version 🚀
on:
  push:
    branches:
      - develop
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Current Code Base
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'
    - name: Create an incremental pre-release tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        PRERELEASE: true
        PRERELEASE_SUFFIX: "alpha"
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.19' # The Go version to download (if necessary) and use.
    - run: GOPROXY=proxy.golang.org go list -m ${{ github.server_url }}/${{ github.repository }}/pulumi@{{needs.tag.outputs.new_tag}}
  validate:
    runs-on: ubuntu-latest
    steps:
    - run: curl ${{ github.server_url }}/${{ github.repository }}/pulumi@{{needs.tag.outputs.new_tag}}