name: Go Module Release
run-name: ${{ github.actor }} is releasing a new Go Module version 🚀
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout Current Code Base
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'
    - name: Create an incremental pre-release tag
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: none
        PRERELEASE: true
        PRERELEASE_SUFFIX: "alpha"